### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by d4rxt4r** [KarmaComputing/container-hosting#37]
sorry for bothering, but i cant open any of containers, created by your service since 1 of september, because ssl certificate is invalid
![image](https://github.com/KarmaComputing/container-hosting/assets/7714963/e3c2bbae-9c17-4746-889d-9b37b5e15427)

the certificate used on main website is valid until 26 of october, which means in 13 days i wont able to open it as well

**Comment by chrisjsimpson** [comment]
Resolved
