### ISSUE TITLE
Cannot change anything

### ISSUE THREAD

**Issue by plsgivemeachane** [KarmaComputing/container-hosting#42]
**Is your feature request related to a problem? Please describe.**
I just cannot change even the source code change the size doesn't change

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisjsimpson** [comment]
> I just cannot change even the source code change the size doesn't change

Hey @plsgivemeachane thanks for trying... which is your repo? It's very hard to help without a link to your repo/code.
