### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by InitialXKO** [KarmaComputing/container-hosting#48]
🐧 In dokku-wrapper.py
🐌 Limiting app CPU resources for app: ******
🧠 Limiting app memory resources for app: ******
✅ Located APP_NAME: ******
🔓 Valid api key
👀 Getting GIT_USERNAME_OR_ORG
✅ Matched GIT_USERNAME_OR_ORG
👀 Getting GIT_REPO_NAME
✅ Matched GIT_REPO_NAME
 !     `secret_ZJ5GDXAUbJj******_BsjQAaqUB-hmo7GMvH9LqOhgPj8E_nM6-xQ8Uhua******0kHov******pSnuwPVfKZgJgu_nsZw9 dokku config:set --no-restart ****** DB_USER=****** DB_PASSWORD=****** DB_HOST=******67.235.74.******45 DB_PORT=****** DB_NAME=db_7xT_ts_******7******8680307 RAILS_DEVELOPMENT_HOSTS=******.containers.anotherwebservice.com DATABASE_URL=*********67.235.74.******45:******/db_7xT_ts_******7******8680307?pool=5 SECRET_KEY=zyPayEs68i3o5unXEQ8nRNr******fZUXErrdxQR-Qbi9 ALLOWED_HOSTS=******.containers.anotherwebservice.com DEBUG=****** DB_ENGINE=****** DB_NAME=db_7xT_ts_******7******8680307 DB_HOST=******67.235.74.******45 DB_USER=****** DB_PASSWORD=****** DB_PORT=******` is not a dokku command.
 !     See `dokku help` for a list of available commands.
⏳ Running: ['dokku', 'config:set', '--no-restart', '******', 'DB_USER=******', 'DB_PASSWORD=******', 'DB_HOST=******67.235.74.******45', 'DB_PORT=******', 'DB_NAME=db_7xT_ts_******7******8680307', 'RAILS_DEVELOPMENT_HOSTS=']
✨ Completed run
+ amber exec -- sh -c 'ssh -F /dev/null dokku@$DOKKU_HOST -C $CONTAINER_HOSTING_API_KEY dokku git:sync --build $APP_NAME https://github.com/InitialXKO/container-r00vp9o.git main'
 !     `secret_ZJ5GDXAUbJj******_BsjQAaqUB-hmo7GMvH9LqOhgPj8E_nM6-xQ8Uhua******0kHov******pSnuwPVfKZgJgu_nsZw9 dokku git:sync --build ****** https://github.com/******/******.git main` is not a dokku command.
 !     See `dokku help` for a list of available commands.
-----> Cloning ****** from https://github.com/******/******.git#main
       Detected branch, setting deploy-branch to main
[******G-----> Cleaning up...
 !     `secret_ZJ5GDXAUbJj******_BsjQAaqUB-hmo7GMvH9LqOhgPj8E_nM6-xQ8Uhua******0kHov******pSnuwPVfKZgJgu_nsZw9 dokku git:sync --build ****** https://github.com/******/******.git main` is not a dokku command.
 !     See `dokku help` for a list of available commands.
#0 building with "default" instance using docker driver
#****** [internal] load build definition from Dockerfile
#****** transferring dockerfile:
#****** transferring dockerfile: ******72B done
#****** DONE 0.7s
#2 [internal] load metadata for docker.io/flowiseai/flowise:******.6.2
#2 DONE 0.8s
#3 [internal] load .dockerignore
#3 transferring context:
#3 transferring context: 2B done
#3 DONE 0.7s
#4 [******/******] FROM docker.io/flowiseai/flowise:******.6.2@sha256:cadf******dc57e******955a4e******0ccfab0e8******36******929******0fd66a8e4ccff965fd6ff7dd3d******99
#4 CACHED
#5 exporting to image
#5 exporting layers 0.0s done
#5 writing image sha256:******a4b76db******7584ba3766bbdc448******38700c60ab55a4204a2ab6dedc839393c******57e 0.0s done
#5 naming to docker.io/dokku/******:latest
#5 naming to docker.io/dokku/******:latest 0.******s done
[******G-----> Building ****** from Dockerfile
[******G-----> Releasing ******...
[******G-----> Checking for predeploy task
[******G       No predeploy task found, skipping
[******G-----> Checking for release task
[******G       No release task found, skipping
[******G-----> Checking for first deploy postdeploy task
[******G       No first deploy postdeploy task found, skipping
#5 DONE 0.******s
[******G=====> Processing deployment checks
[******G       No web healthchecks found in app.json. Simple container checks will be performed.
[******G       For more efficient zero downtime deployments, add healthchecks to your app.json. See https://dokku.com/docs/deployment/zero-downtime-deploys/ for examples
[******G-----> Deploying ****** via the docker-local scheduler...
[******G-----> Deploying web (count=******)
[******G       Attempting pre-flight checks (web.******)
[******G-----> Executing 2 healthchecks                                                        
[******G       Running healthcheck name='default' type='uptime' uptime=******0                      
[******G       Running healthcheck name='port listening check' attempts=3 port=3000 retries=2 timeout=5 type='listening' wait=5
[******G       Healthcheck succeeded name='port listening check'                               
[******G       Healthcheck succeeded name='default'                                            
[******G       All checks successful (web.******)
[******G=====> Start of ****** container output (web.******)
[******G       [202](https://github.com/InitialXKO/container-r00vp9o/actions/runs/9558355485/job/26346937418#step:8:203)4-06-******8 03:******3:******3 [INFO]: Starting Flowise...
[******G       2024-06-******8 03:******3:******3 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
[******G       2024-06-******8 03:******3:******3 [INFO]: 📦 [server]: Data Source is being initialized!
[******G       2024-06-******8 03:******3:******8 [INFO]: 📦 [server]: Data Source has been initialized!
[******G=====> End of ****** container output (web.******)
[******G=====> Triggering early nginx proxy rebuild
[******G-----> Ensuring network configuration is in sync for ******
[******G-----> Configuring ******.containers.anotherwebservice.com...(using built-in template)
[******G-----> Creating http nginx.conf
[******G       Reloading nginx
[******G-----> Running post-deploy
[******G-----> Ensuring network configuration is in sync for ******
[******G-----> Configuring ******.containers.anotherwebservice.com...(using built-in template)
[******G-----> Creating http nginx.conf
[******G       Reloading nginx
[******G-----> Renaming containers
[******G       Renaming container ******.web.******.upcoming-29998 (ea882b888d98) to ******.web.******
[******G-----> Checking for postdeploy task
*****m*****m !     No healthchecks found in app.json for web process type                          
client_loop: send disconnect: Broken pipe
[******G       No postdeploy task found, skipping
Error: Process completed with exit code 255.

**Comment by chrisjsimpson** [comment]
@InitialXKO consider trying again
